<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class FullStoreFeatures extends Migration {
 public function up(){
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'product_id'=>['type'=>'INT','unsigned'=>true],'customer_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'name'=>['type'=>'VARCHAR','constraint'=>120],'email'=>['type'=>'VARCHAR','constraint'=>160,'null'=>true],'rating'=>['type'=>'TINYINT','default'=>5],'title'=>['type'=>'VARCHAR','constraint'=>180,'null'=>true],'review'=>['type'=>'TEXT'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'pending'],'created_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addKey('product_id');$this->forge->createTable('product_reviews',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'slug'=>['type'=>'VARCHAR','constraint'=>100,'unique'=>true],'title'=>['type'=>'VARCHAR','constraint'=>180],'content'=>['type'=>'TEXT'],'meta_title'=>['type'=>'VARCHAR','constraint'=>180,'null'=>true],'meta_description'=>['type'=>'VARCHAR','constraint'=>320,'null'=>true],'active'=>['type'=>'TINYINT','default'=>1],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('content_pages',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'name'=>['type'=>'VARCHAR','constraint'=>120],'email'=>['type'=>'VARCHAR','constraint'=>160],'phone'=>['type'=>'VARCHAR','constraint'=>25,'null'=>true],'subject'=>['type'=>'VARCHAR','constraint'=>180],'message'=>['type'=>'TEXT'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'new'],'created_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('contact_messages',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'email'=>['type'=>'VARCHAR','constraint'=>160,'unique'=>true],'active'=>['type'=>'TINYINT','default'=>1],'created_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('newsletter_subscribers',true);
  $this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'event_name'=>['type'=>'VARCHAR','constraint'=>80],'path'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'product_id'=>['type'=>'INT','null'=>true],'customer_id'=>['type'=>'INT','null'=>true],'meta'=>['type'=>'TEXT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('analytics_events',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'session_key'=>['type'=>'VARCHAR','constraint'=>100,'unique'=>true],'customer_id'=>['type'=>'INT','null'=>true],'email'=>['type'=>'VARCHAR','constraint'=>160,'null'=>true],'cart_json'=>['type'=>'LONGTEXT'],'total'=>['type'=>'DECIMAL','constraint'=>'10,2','default'=>0],'recovered'=>['type'=>'TINYINT','default'=>0],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('abandoned_carts',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'channel'=>['type'=>'VARCHAR','constraint'=>30],'recipient'=>['type'=>'VARCHAR','constraint'=>180],'subject'=>['type'=>'VARCHAR','constraint'=>200,'null'=>true],'message'=>['type'=>'TEXT'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'queued'],'created_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('notification_queue',true);
  $cols=$this->db->getFieldNames('products');
  foreach(['care_instructions TEXT NULL','dimensions VARCHAR(160) NULL','weight VARCHAR(60) NULL','hsn_code VARCHAR(40) NULL','tax_rate DECIMAL(5,2) NOT NULL DEFAULT 3.00','video_url VARCHAR(255) NULL'] as $sql){$name=strtok($sql,' ');if(!in_array($name,$cols))$this->db->query('ALTER TABLE products ADD COLUMN '.$sql);}
  $ocols=$this->db->getFieldNames('orders');
  foreach(['coupon_code VARCHAR(50) NULL','discount DECIMAL(10,2) NOT NULL DEFAULT 0','tracking_number VARCHAR(100) NULL','tracking_url VARCHAR(255) NULL','payment_status VARCHAR(30) NOT NULL DEFAULT \'Pending\''] as $sql){$name=strtok($sql,' ');if(!in_array($name,$ocols))$this->db->query('ALTER TABLE orders ADD COLUMN '.$sql);}
  $pages=[
   ['slug'=>'about','title'=>'About Elores','content'=>'Elores creates contemporary jewellery for everyday elegance. Our focus is wearable design, thoughtful finishes and gift-ready presentation.'],
   ['slug'=>'faq','title'=>'Frequently Asked Questions','content'=>'Shipping: Orders are normally dispatched in 1–2 business days.\nReturns: Eligible unused items can be requested for return within 7 days of delivery.\nCare: Keep jewellery dry, avoid perfume contact and store pieces separately.'],
   ['slug'=>'privacy','title'=>'Privacy Policy','content'=>'We use customer information only to process orders, provide support and improve the shopping experience. We do not sell customer personal information.'],
   ['slug'=>'terms','title'=>'Terms & Conditions','content'=>'By placing an order with Elores you agree to the prices, product information, payment, shipping and return terms displayed on this website.'],
   ['slug'=>'shipping','title'=>'Shipping Policy','content'=>'We ship across India. Shipping charges and free-shipping thresholds are shown at checkout. Delivery timelines vary by destination.'],
   ['slug'=>'returns','title'=>'Return & Refund Policy','content'=>'Eligible unused products in original packaging may be returned within 7 days of delivery. Refunds are processed after inspection.'],
   ['slug'=>'care','title'=>'Jewellery Care Guide','content'=>'Keep jewellery away from water, perfume and harsh chemicals. Wipe with a soft dry cloth after use and store separately in a dry pouch.']
  ]; foreach($pages as $p){$p['meta_title']=$p['title'].' | Elores';$p['meta_description']=substr($p['content'],0,300);$p['active']=1;$p['updated_at']=date('Y-m-d H:i:s');$this->db->table('content_pages')->ignore(true)->insert($p);} 
  $settings=[['setting_key'=>'whatsapp','setting_value'=>''],['setting_key'=>'address','setting_value'=>'India'],['setting_key'=>'return_days','setting_value'=>'7'],['setting_key'=>'announcement','setting_value'=>'FREE SHIPPING ABOVE ₹999 • COD AVAILABLE • EASY 7-DAY RETURNS'],['setting_key'=>'google_analytics_id','setting_value'=>''],['setting_key'=>'meta_title','setting_value'=>'Elores — Modern Jewellery'],['setting_key'=>'meta_description','setting_value'=>'Shop modern everyday jewellery at Elores.'],['setting_key'=>'currency','setting_value'=>'INR']];foreach($settings as $s)$this->db->table('store_settings')->ignore(true)->insert($s);
 }
 public function down(){foreach(['notification_queue','abandoned_carts','analytics_events','newsletter_subscribers','contact_messages','content_pages','product_reviews'] as $t)$this->forge->dropTable($t,true);}
}
