<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class ExpandEcommerce extends Migration {
 public function up(){
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'name'=>['type'=>'VARCHAR','constraint'=>120],'email'=>['type'=>'VARCHAR','constraint'=>160,'unique'=>true],'phone'=>['type'=>'VARCHAR','constraint'=>25,'null'=>true],'password'=>['type'=>'VARCHAR','constraint'=>255],'active'=>['type'=>'TINYINT','default'=>1],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('customers',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'customer_id'=>['type'=>'INT','unsigned'=>true],'label'=>['type'=>'VARCHAR','constraint'=>50,'default'=>'Home'],'name'=>['type'=>'VARCHAR','constraint'=>120],'phone'=>['type'=>'VARCHAR','constraint'=>25],'address'=>['type'=>'TEXT'],'city'=>['type'=>'VARCHAR','constraint'=>80],'state'=>['type'=>'VARCHAR','constraint'=>80],'pincode'=>['type'=>'VARCHAR','constraint'=>12],'is_default'=>['type'=>'TINYINT','default'=>0]]);$this->forge->addKey('id',true);$this->forge->createTable('customer_addresses',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'title'=>['type'=>'VARCHAR','constraint'=>180],'subtitle'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'image'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'button_text'=>['type'=>'VARCHAR','constraint'=>80,'null'=>true],'button_url'=>['type'=>'VARCHAR','constraint'=>255,'default'=>'/shop'],'sort_order'=>['type'=>'INT','default'=>0],'active'=>['type'=>'TINYINT','default'=>1],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('banners',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'setting_key'=>['type'=>'VARCHAR','constraint'=>120,'unique'=>true],'setting_value'=>['type'=>'TEXT','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('store_settings',true);
  $this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'code'=>['type'=>'VARCHAR','constraint'=>50,'unique'=>true],'type'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'percent'],'value'=>['type'=>'DECIMAL','constraint'=>'10,2'],'min_order'=>['type'=>'DECIMAL','constraint'=>'10,2','default'=>0],'active'=>['type'=>'TINYINT','default'=>1],'expires_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->createTable('coupons',true);
  foreach(['sku VARCHAR(80) NULL','short_description TEXT NULL','meta_title VARCHAR(180) NULL','meta_description VARCHAR(320) NULL','meta_keywords VARCHAR(255) NULL','image VARCHAR(255) NULL','featured TINYINT NOT NULL DEFAULT 0','is_new TINYINT NOT NULL DEFAULT 0'] as $sql) $this->db->query('ALTER TABLE products ADD COLUMN '.$sql);
  $this->db->query('ALTER TABLE orders ADD COLUMN customer_id INT NULL');
  $this->db->table('banners')->insertBatch([['title'=>'Timeless beauty, everyday elegance','subtitle'=>'Modern jewellery designed to make every day feel special.','image'=>'/elores-logo.png','button_text'=>'SHOP NOW','button_url'=>'/shop','sort_order'=>1,'active'=>1],['title'=>'New season, new shine','subtitle'=>'Discover lightweight pieces for effortless styling.','image'=>'/elores-logo.png','button_text'=>'NEW ARRIVALS','button_url'=>'/shop','sort_order'=>2,'active'=>1]]);
  $this->db->table('store_settings')->insertBatch([['setting_key'=>'store_name','setting_value'=>'Elores'],['setting_key'=>'logo','setting_value'=>'/elores-logo.png'],['setting_key'=>'support_email','setting_value'=>'support@elores.local'],['setting_key'=>'support_phone','setting_value'=>'+91 99999 99999'],['setting_key'=>'free_shipping_min','setting_value'=>'999'],['setting_key'=>'instagram','setting_value'=>''],['setting_key'=>'facebook','setting_value'=>'']]);
 }
 public function down(){foreach(['coupons','store_settings','banners','customer_addresses','customers'] as $t)$this->forge->dropTable($t,true);}
}