<?php namespace App\Controllers\Api; use App\Models\ProductModel;
class AdminProducts extends BaseApi {
 private function guard($action='view'){return $this->adminCan('products',$action);}
 private function withImages(array $rows): array { $db=db_connect(); foreach($rows as &$r){$imgs=$db->table('product_images')->select('image')->where('product_id',$r['id'])->orderBy('sort_order')->get()->getResultArray();$r['images']=array_column($imgs,'image');if(!$r['images']&&!empty($r['image']))$r['images']=[$r['image']];} return $rows; }
 private function syncImages(int $id,array $images): void {$images=array_values(array_unique(array_filter($images)));if(count($images)<1||count($images)>5)throw new \RuntimeException('Product requires 1 to 5 images');$db=db_connect();$db->table('product_images')->where('product_id',$id)->delete();foreach($images as $i=>$url)$db->table('product_images')->insert(['product_id'=>$id,'image'=>$url,'sort_order'=>$i,'is_primary'=>$i===0?1:0,'created_at'=>date('Y-m-d H:i:s')]);$db->table('products')->where('id',$id)->update(['image'=>$images[0]]);}
 public function index(){if(!$this->guard('view'))return $this->ok(['message'=>'Unauthorized'],401);$rows=db_connect()->table('products p')->select('p.*,c.name category_name')->join('categories c','c.id=p.category_id','left')->orderBy('p.id','DESC')->get()->getResultArray();return $this->ok(['data'=>$this->withImages($rows)]);}
 public function create(){if(!$this->guard('add'))return $this->ok(['message'=>'Unauthorized'],401);$d=$this->json();$images=$d['images']??[];unset($d['images'],$d['id'],$d['category_name']);if(empty($d['name'])||empty($d['category_id']))return $this->ok(['message'=>'Name and category are required'],422);if(count($images)<1||count($images)>5)return $this->ok(['message'=>'Upload minimum 1 and maximum 5 product images'],422);$d['slug']=!empty($d['slug'])?url_title($d['slug'],'-',true):url_title($d['name'],'-',true);$d['active']=isset($d['active'])?(int)$d['active']:1;$d['image']=$images[0];if(db_connect()->table('products')->where('slug',$d['slug'])->countAllResults())return $this->ok(['message'=>'Product slug already exists'],409);$id=(new ProductModel())->insert($d,true);try{$this->syncImages((int)$id,$images);}catch(\Throwable $e){(new ProductModel())->delete($id);return $this->ok(['message'=>$e->getMessage()],422);}return $this->ok(['message'=>'Product created','id'=>$id],201);}
 public function update($id=null){if(!$this->guard('edit'))return $this->ok(['message'=>'Unauthorized'],401);$d=$this->json();$images=$d['images']??null;unset($d['images'],$d['id'],$d['category_name']);if(isset($d['name']))$d['slug']=!empty($d['slug'])?url_title($d['slug'],'-',true):url_title($d['name'],'-',true);if($images!==null){if(count($images)<1||count($images)>5)return $this->ok(['message'=>'Upload minimum 1 and maximum 5 product images'],422);$d['image']=$images[0];}(new ProductModel())->update((int)$id,$d);if($images!==null)$this->syncImages((int)$id,$images);return $this->ok(['message'=>'Product updated']);}
 public function delete($id=null){if(!$this->guard('delete'))return $this->ok(['message'=>'Unauthorized'],401);$db=db_connect();$db->table('product_images')->where('product_id',(int)$id)->delete();(new ProductModel())->delete((int)$id);return $this->ok(['message'=>'Product deleted']);}
}
