<?php namespace App\Controllers\Api;
class AdminManage extends BaseApi {
 private function guard($module,$action='view'){return $this->adminCan($module,$action);}
 public function customers(){if(!$this->guard('customers'))return $this->ok(['message'=>'Forbidden'],403);return $this->ok(['data'=>db_connect()->table('customers')->select('id,name,email,phone,active,created_at')->orderBy('id','DESC')->get()->getResultArray()]);}
 public function banners(){if(!$this->guard('carousel'))return $this->ok(['message'=>'Forbidden'],403);return $this->ok(['data'=>db_connect()->table('banners')->orderBy('sort_order')->get()->getResultArray()]);}
 public function saveBanner($id=null){if(!$this->guard('carousel',$id?'edit':'add'))return $this->ok(['message'=>'Forbidden'],403);$d=$this->json();$row=['title'=>$d['title']??'','subtitle'=>$d['subtitle']??'','image'=>$d['image']??'/elores-logo.png','button_text'=>$d['button_text']??'SHOP NOW','button_url'=>$d['button_url']??'/shop','sort_order'=>(int)($d['sort_order']??0),'active'=>(int)($d['active']??1),'updated_at'=>date('Y-m-d H:i:s')];$b=db_connect()->table('banners');if($id)$b->where('id',(int)$id)->update($row);else{$row['created_at']=date('Y-m-d H:i:s');$b->insert($row);}return $this->ok(['message'=>'Banner saved']);}
 public function deleteBanner($id=null){if(!$this->guard('carousel','delete'))return $this->ok(['message'=>'Forbidden'],403);db_connect()->table('banners')->where('id',(int)$id)->delete();return $this->ok(['message'=>'Banner deleted']);}
 public function settings(){if(!$this->guard('settings','edit'))return $this->ok(['message'=>'Forbidden'],403);$d=$this->json();$db=db_connect();foreach($d as $k=>$v){$b=$db->table('store_settings');if($b->where('setting_key',$k)->countAllResults())$db->table('store_settings')->where('setting_key',$k)->update(['setting_value'=>(string)$v]);else$db->table('store_settings')->insert(['setting_key'=>$k,'setting_value'=>(string)$v]);}return $this->ok(['message'=>'Settings saved']);}
 public function coupons(){if(!$this->guard('coupons'))return $this->ok(['message'=>'Forbidden'],403);return $this->ok(['data'=>db_connect()->table('coupons')->orderBy('id','DESC')->get()->getResultArray()]);}
 public function saveCoupon($id=null){if(!$this->guard('coupons',$id?'edit':'add'))return $this->ok(['message'=>'Forbidden'],403);$d=$this->json();$row=['code'=>strtoupper($d['code']??''),'type'=>$d['type']??'percent','value'=>(float)($d['value']??0),'min_order'=>(float)($d['min_order']??0),'active'=>(int)($d['active']??1),'expires_at'=>($d['expires_at']??'')?:null];$b=db_connect()->table('coupons');if($id){$b->where('id',(int)$id)->update($row);return $this->ok(['message'=>'Coupon updated']);}$b->insert($row);return $this->ok(['message'=>'Coupon created'],201);}
 public function deleteCoupon($id=null){if(!$this->guard('coupons','delete'))return $this->ok(['message'=>'Forbidden'],403);db_connect()->table('coupons')->where('id',(int)$id)->delete();return $this->ok(['message'=>'Coupon deleted']);}
}
