<?php namespace App\Controllers\Api;
class Auth extends BaseApi {
 private function token($email){$s=getenv('ELORES_CUSTOMER_SECRET')?:'elores-customer-secret';return base64_encode($email.'|'.hash_hmac('sha256',$email,$s));}
 private function current(){ $h=$this->request->getHeaderLine('Authorization');if(!preg_match('/Bearer\s+(.+)/i',$h,$m))return null;$raw=base64_decode(trim($m[1]),true);if(!$raw||!str_contains($raw,'|'))return null;[$e,$sig]=explode('|',$raw,2);$s=getenv('ELORES_CUSTOMER_SECRET')?:'elores-customer-secret';return hash_equals(hash_hmac('sha256',$e,$s),$sig)?$e:null; }
 public function register(){ $d=$this->json();foreach(['name','email','password'] as $k)if(empty($d[$k]))return $this->ok(['message'=>"$k is required"],422);$db=db_connect();if($db->table('customers')->where('email',strtolower($d['email']))->countAllResults())return $this->ok(['message'=>'Email already registered'],409);$db->table('customers')->insert(['name'=>$d['name'],'email'=>strtolower($d['email']),'phone'=>$d['phone']??'','password'=>password_hash($d['password'],PASSWORD_DEFAULT),'active'=>1,'created_at'=>date('Y-m-d H:i:s')]);return $this->ok(['message'=>'Registration successful','token'=>$this->token(strtolower($d['email']))],201); }
 public function login(){ $d=$this->json();$u=db_connect()->table('customers')->where('email',strtolower($d['email']??''))->where('active',1)->get()->getRowArray();if(!$u||!password_verify($d['password']??'',$u['password']))return $this->ok(['message'=>'Invalid email or password'],401);return $this->ok(['token'=>$this->token($u['email']),'user'=>['id'=>$u['id'],'name'=>$u['name'],'email'=>$u['email'],'phone'=>$u['phone']]]); }
 public function forgot(){ $email=strtolower($this->json()['email']??'');if(!$email)return $this->ok(['message'=>'Email required'],422);return $this->ok(['message'=>'Demo OTP generated','otp'=>'123456']); }
 public function reset(){ $d=$this->json();if(($d['otp']??'')!=='123456')return $this->ok(['message'=>'Invalid OTP'],422);$email=strtolower($d['email']??'');if(empty($d['password']))return $this->ok(['message'=>'New password required'],422);db_connect()->table('customers')->where('email',$email)->update(['password'=>password_hash($d['password'],PASSWORD_DEFAULT),'updated_at'=>date('Y-m-d H:i:s')]);return $this->ok(['message'=>'Password reset successful']); }
 public function me(){ $e=$this->current();if(!$e)return $this->ok(['message'=>'Unauthorized'],401);$u=db_connect()->table('customers')->select('id,name,email,phone,created_at')->where('email',$e)->get()->getRowArray();return $this->ok(['user'=>$u]); }
 public function orders(){ $e=$this->current();if(!$e)return $this->ok(['message'=>'Unauthorized'],401);$u=db_connect()->table('customers')->where('email',$e)->get()->getRowArray();$rows=db_connect()->table('orders')->where('customer_id',$u['id'])->orderBy('id','DESC')->get()->getResultArray();return $this->ok(['data'=>$rows]); }
}