<?php namespace App\Controllers\Api;
class Commerce extends BaseApi {
 private function customerEmail(){ $h=$this->request->getHeaderLine('Authorization');if(!preg_match('/Bearer\s+(.+)/i',$h,$m))return null;$raw=base64_decode(trim($m[1]),true);if(!$raw||!str_contains($raw,'|'))return null;[$e,$sig]=explode('|',$raw,2);$s=getenv('ELORES_CUSTOMER_SECRET')?:'elores-customer-secret';return hash_equals(hash_hmac('sha256',$e,$s),$sig)?$e:null; }
 private function customer(){ $e=$this->customerEmail();return $e?db_connect()->table('customers')->where('email',$e)->get()->getRowArray():null; }
 public function suggestions(){ $q=trim((string)$this->request->getGet('q'));if(strlen($q)<2)return $this->ok(['data'=>[]]);$rows=db_connect()->table('products')->select('name,slug,image')->where('active',1)->like('name',$q)->limit(8)->get()->getResultArray();return $this->ok(['data'=>$rows]); }
 public function reviews($productId=null){$rows=db_connect()->table('product_reviews')->where('product_id',(int)$productId)->where('status','approved')->orderBy('id','DESC')->get()->getResultArray();$avg=$rows?array_sum(array_column($rows,'rating'))/count($rows):0;return $this->ok(['data'=>$rows,'average'=>round($avg,1),'count'=>count($rows)]);}
 public function reviewCreate($productId=null){$d=$this->json();if(empty($d['name'])||empty($d['review']))return $this->ok(['message'=>'Name and review are required'],422);$c=$this->customer();db_connect()->table('product_reviews')->insert(['product_id'=>(int)$productId,'customer_id'=>$c['id']??null,'name'=>trim($d['name']),'email'=>trim($d['email']??($c['email']??'')),'rating'=>max(1,min(5,(int)($d['rating']??5))),'title'=>trim($d['title']??''),'review'=>trim($d['review']),'image'=>$d['image']??null,'status'=>'pending','created_at'=>date('Y-m-d H:i:s')]);return $this->ok(['message'=>'Review submitted for approval'],201);}
 public function page($slug=null){$r=db_connect()->table('content_pages')->where('slug',$slug)->where('active',1)->get()->getRowArray();return $r?$this->ok(['data'=>$r]):$this->ok(['message'=>'Page not found'],404);}
 public function contact(){ $d=$this->json();foreach(['name','email','subject','message'] as $k)if(empty($d[$k]))return $this->ok(['message'=>"$k is required"],422);db_connect()->table('contact_messages')->insert(['name'=>$d['name'],'email'=>$d['email'],'phone'=>$d['phone']??'','subject'=>$d['subject'],'message'=>$d['message'],'status'=>'new','created_at'=>date('Y-m-d H:i:s')]);return $this->ok(['message'=>'Thanks. We have received your message.'],201); }
 public function newsletter(){ $email=strtolower(trim($this->json()['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))return $this->ok(['message'=>'Valid email required'],422);$b=db_connect()->table('newsletter_subscribers');if(!$b->where('email',$email)->countAllResults())$b->insert(['email'=>$email,'active'=>1,'created_at'=>date('Y-m-d H:i:s')]);return $this->ok(['message'=>'Subscribed successfully']);}
 public function coupon(){ $d=$this->json();$code=strtoupper(trim($d['code']??''));$subtotal=(float)($d['subtotal']??0);$r=db_connect()->table('coupons')->where('code',$code)->where('active',1)->get()->getRowArray();if(!$r||($r['expires_at']&&strtotime($r['expires_at'])<time()))return $this->ok(['message'=>'Invalid or expired coupon'],422);if($subtotal<(float)$r['min_order'])return $this->ok(['message'=>'Minimum order is '.(float)$r['min_order']],422);$discount=$r['type']==='percent'?$subtotal*((float)$r['value']/100):min($subtotal,(float)$r['value']);return $this->ok(['code'=>$code,'discount'=>round($discount,2)]);}
 public function track(){ $d=$this->json();$c=$this->customer();db_connect()->table('analytics_events')->insert(['event_name'=>substr($d['event_name']??'page_view',0,80),'path'=>substr($d['path']??'',0,255),'product_id'=>isset($d['product_id'])?(int)$d['product_id']:null,'customer_id'=>$c['id']??null,'meta'=>json_encode($d['meta']??[]),'created_at'=>date('Y-m-d H:i:s')]);return $this->ok(['ok'=>true]); }
 public function cart(){ $d=$this->json();$key=substr($d['session_key']??'',0,100);if(!$key)return $this->ok(['message'=>'session_key required'],422);$c=$this->customer();$row=['session_key'=>$key,'customer_id'=>$c['id']??null,'email'=>$d['email']??($c['email']??null),'cart_json'=>json_encode($d['cart']??[]),'total'=>(float)($d['total']??0),'updated_at'=>date('Y-m-d H:i:s')];$b=db_connect()->table('abandoned_carts');if($b->where('session_key',$key)->countAllResults())$b->where('session_key',$key)->update($row);else$b->insert($row);return $this->ok(['ok'=>true]); }
 public function addresses(){ $c=$this->customer();if(!$c)return $this->ok(['message'=>'Unauthorized'],401);return $this->ok(['data'=>db_connect()->table('customer_addresses')->where('customer_id',$c['id'])->orderBy('is_default','DESC')->get()->getResultArray()]); }
 public function addressSave(){ $c=$this->customer();if(!$c)return $this->ok(['message'=>'Unauthorized'],401);$d=$this->json();foreach(['name','phone','address','city','state','pincode'] as $k)if(empty($d[$k]))return $this->ok(['message'=>"$k is required"],422);$db=db_connect();if(!empty($d['is_default']))$db->table('customer_addresses')->where('customer_id',$c['id'])->update(['is_default'=>0]);$db->table('customer_addresses')->insert(['customer_id'=>$c['id'],'label'=>$d['label']??'Home','name'=>$d['name'],'phone'=>$d['phone'],'address'=>$d['address'],'city'=>$d['city'],'state'=>$d['state'],'pincode'=>$d['pincode'],'is_default'=>!empty($d['is_default'])?1:0]);return $this->ok(['message'=>'Address saved'],201); }
 public function adminReviews(){if(!$this->adminCan('reviews','view'))return $this->ok(['message'=>'Forbidden'],403);$rows=db_connect()->table('product_reviews r')->select('r.*,p.name product_name')->join('products p','p.id=r.product_id','left')->orderBy('r.id','DESC')->get()->getResultArray();return $this->ok(['data'=>$rows]);}
 public function adminReview($id=null){if(!$this->adminCan('reviews','edit'))return $this->ok(['message'=>'Forbidden'],403);$d=$this->json();db_connect()->table('product_reviews')->where('id',(int)$id)->update(['status'=>$d['status']??'approved']);return $this->ok(['message'=>'Review updated']);}
 public function adminPages(){if(!$this->adminCan('pages','view'))return $this->ok(['message'=>'Forbidden'],403);return $this->ok(['data'=>db_connect()->table('content_pages')->orderBy('title')->get()->getResultArray()]);}
 public function adminPage($id=null){if(!$this->adminCan('pages',$id?'edit':'add'))return $this->ok(['message'=>'Forbidden'],403);$d=$this->json();$row=['title'=>$d['title']??'','slug'=>url_title($d['slug']??($d['title']??''),'-',true),'content'=>$d['content']??'','meta_title'=>$d['meta_title']??'','meta_description'=>$d['meta_description']??'','active'=>(int)($d['active']??1),'updated_at'=>date('Y-m-d H:i:s')];$b=db_connect()->table('content_pages');if($id)$b->where('id',(int)$id)->update($row);else$b->insert($row);return $this->ok(['message'=>'Page saved']);}
 public function adminMessages(){if(!$this->adminCan('messages','view'))return $this->ok(['message'=>'Forbidden'],403);return $this->ok(['data'=>db_connect()->table('contact_messages')->orderBy('id','DESC')->get()->getResultArray()]);}
 public function adminAnalytics(){if(!$this->adminCan('analytics','view'))return $this->ok(['message'=>'Forbidden'],403);$db=db_connect();$events=$db->table('analytics_events')->select('event_name,COUNT(*) total')->groupBy('event_name')->get()->getResultArray();$carts=$db->table('abandoned_carts')->where('recovered',0)->countAllResults();$subs=$db->table('newsletter_subscribers')->where('active',1)->countAllResults();return $this->ok(['events'=>$events,'abandoned_carts'=>$carts,'subscribers'=>$subs]);}
 public function reviewUpload(){ $file=$this->request->getFile('file');if(!$file||!$file->isValid())return $this->ok(['message'=>'Valid image required'],422);if($file->getSize()>2*1024*1024)return $this->ok(['message'=>'Image must be 2MB or smaller'],422);if(!in_array($file->getMimeType(),['image/jpeg','image/png','image/webp','image/avif']))return $this->ok(['message'=>'Only JPG, PNG, WebP or AVIF allowed'],422);$name=$file->getRandomName();$dir=FCPATH.'uploads/reviews';if(!is_dir($dir))mkdir($dir,0755,true);$file->move($dir,$name);return $this->ok(['url'=>base_url('uploads/reviews/'.$name)]);}
 public function adminUpload(){if(!$this->adminOrFail())return $this->ok(['message'=>'Unauthorized'],401);$file=$this->request->getFile('file');if(!$file||!$file->isValid())return $this->ok(['message'=>'Valid file required'],422);if($file->getSize()>2*1024*1024)return $this->ok(['message'=>'Image must be 2MB or smaller'],422);if(!in_array($file->getMimeType(),['image/jpeg','image/png','image/webp','image/avif']))return $this->ok(['message'=>'Only JPG, PNG, WebP or AVIF allowed'],422);$name=$file->getRandomName();$dir=FCPATH.'uploads';if(!is_dir($dir))mkdir($dir,0755,true);$file->move($dir,$name);return $this->ok(['url'=>base_url('uploads/'.$name)]);}
}
